/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 DAILYAPPS.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/DAILYAPPS.gltf');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Plane" position={[0.002, 0.157, 0.003]}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
        </group>
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.001']} position={[-2.04, -0.03, 1.616]} scale={0.743} />
        <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials['Material.007']} position={[-2.04, -0.089, 1.616]} scale={0.743} />
        <group name="Text002" position={[-2.04, 0.059, 1.616]} scale={[0.743, 0.037, 0.743]}>
          <mesh name="Text002_1" geometry={nodes.Text002_1.geometry} material={materials['Material.006']} />
          <mesh name="Text002_2" geometry={nodes.Text002_2.geometry} material={materials['Material.008']} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/DAILYAPPS.gltf');
