/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 monstre.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/monstre.gltf');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0.271, 0.611, -0.058]} rotation={[-0.073, 0, 0]} scale={[0.373, 0.453, 0.373]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone008} />
          <primitive object={nodes.Bone019} />
          <primitive object={nodes.Bone024} />
          <group name="BézierCurve001">
            <skinnedMesh name="BézierCurve003" geometry={nodes.BézierCurve003.geometry} material={materials['Material.001']} skeleton={nodes.BézierCurve003.skeleton} />
            <skinnedMesh name="BézierCurve003_1" geometry={nodes.BézierCurve003_1.geometry} material={materials['Material.007']} skeleton={nodes.BézierCurve003_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/monstre.gltf');
